memcmahon/bike-share

Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/assets/stylesheets/application.scss

N/A
Changes Made:
Adds gems for bootstrap and font-awesome
Configures asset/application.scss
Configure javascript/application.js
Reviewers:
Everyone!

Adds gems for bootstrap and font awesome

---

config/routes.rb

N/A
Changes Made:
Adds initial route structure
Reviewers:

Adds initial route structure

---

config/environments/production.rb

Changes Made:
Updates config.assets.compile to true for production dbs
Reviewers:

Updates config.assets.compile to true

---

app/controllers/application_controller.rb
app/controllers/sessions_controller.rb
app/controllers/users_controller.rb
app/models/accessory.rb
app/models/cart.rb
app/models/order.rb
app/models/user.rb
app/views/layouts/application.html.erb
app/views/sessions/new.html.erb
app/views/users/new.html.erb
db/migrate/20180218000828_add_default_value_to_role_attribute.rb
db/migrate/20180218004003_change_user_id_on_orders.rb
db/schema.rb
spec/features/authentication/logged_in_user_can_log_out_spec.rb
spec/features/authentication/registered_user_can_log_in_spec.rb
spec/features/authentication/visitor_can_create_user_profile_spec.rb
spec/models/accessory_spec.rb
spec/models/cart_spec.rb
spec/models/order_spec.rb
spec/models/user_spec.rb

#30 
Changes Made:
Adds model tests and models for users, cart, accessories, and orders
Adds controllers for sessions and users(non-admins)
Updates migrations for default role values and user_id on orders
Creates feature specs for user creation, login and logout (need to update log out with later views"
implements default user authentication (sessions, flash messages, login/logout)
Reviewers:
@garcia50 @AtmaVichara

Authentication

---

app/assets/stylesheets/_forms.scss
app/assets/stylesheets/_navbar.scss
app/assets/stylesheets/application.scss
app/assets/stylesheets/skeleton.scss
app/views/layouts/application.html.erb
app/views/sessions/new.html.erb
app/views/users/new.html.erb
app/views/welcome/index.html.erb

N/A
Changes Made:
Added styling to new links in navbar and minor touches to refactor out extraneous divs
Added styling to forms for sign up and log in page
Added _forms.scss file
Reviewers:
Megan & Luis

Navbar styling

---

.gitignore
db/seeds.rb

Changes Made:
Add CSV folder, ready to seed 
Reviewers:

Add CSV folder

---

Gemfile
Gemfile.lock
app/controllers/conditions_controller.rb
app/views/conditions/index.html.erb
app/views/layouts/application.html.erb
spec/factories.rb
spec/features/conditions/user_sees_all_conditions_spec.rb
spec/rails_helper.rb

n/a
Changes Made:
* Added FactoryBot gem
* Added factories.rb to spec/
* Added conditions index spec
* Added conditions controller
* Added conditions index view
Reviewers:
Megan & Luis

User conditions

---

Gemfile
Gemfile.lock
app/controllers/trips_controller.rb
app/views/trips/index.html.erb
app/views/trips/show.html.erb
spec/factories.rb
spec/features/trips/visitor_sees_trip_index_spec.rb
spec/features/trips/visitor_sees_trips_show_spec.rb

#27 #26 
Changes Made:
Adds gem 'will_paginate'
Adds specs for visitor trip show and visitor trip index
Adds trips controller with index and show actions
Adds views for trip index and show (visitor)
Reviewers:
@AtmaVichara or @garcia50

Visitor trips

---

.gitignore
app/controllers/application_controller.rb
app/controllers/stations_controller.rb
app/controllers/stations_dashboard.rb
app/models/station.rb
app/views/stations/index.html.erb
app/views/stations/show.html.erb
db/migrate/20180219060342_add_slug_to_stations.rb
db/schema.rb
spec/factories.rb
spec/features/stations/registered_user_sees_stations_dashboard.rb
spec/features/stations/visitor_sees_station_index_spec.rb
spec/features/stations/visitor_sees_station_show_spec.rb

Changes Made:
Created Stations test, controller, view
, added slug column in Station migration. 
Reviewers:

Visitor station show

---

.gitignore
app/assets/stylesheets/_conditions.scss
app/assets/stylesheets/_forms.scss
app/assets/stylesheets/_navbar.scss
app/assets/stylesheets/application.scss
app/assets/stylesheets/skeleton.scss
app/controllers/conditions_controller.rb
app/controllers/conditions_dashboard_controller.rb
app/models/condition.rb
app/views/conditions/index.html.erb
app/views/conditions/show.html.erb
app/views/conditions_dashboard/index.html.erb
config/routes.rb
spec/factories.rb
spec/features/conditions/registered_user_and_admin_sees_weather_dashboard_spec.rb
spec/features/conditions/visitor_sees_all_conditions_spec.rb
spec/features/users/user_sees_all_conditions_spec.rb
spec/models/condition_spec.rb

#52 Started On
Changes Made:
Add containers and panels to conditions index for styling needs
Add pagination
Add conditions dashboard controller
Add spec for viewing weather-dashboard (conditions)
Add index view for weather-dashboard
Add instance method to conditions model
Add test for instance method
All tests passing
Reviewers:
Luis & Megan

Add Some Conditions Styling

---

app/controllers/trips_dashboard_controller.rb
app/models/trip.rb
app/views/trips_dashboard/index.html.erb
spec/features/trips/user_sees_trip_dashboard_spec.rb

#53 #50 
Changes Made:
Adds feature tests and implementation for trip analytics: 
* Weather on the day with the highest rides.
* Weather on the day with the lowest rides.
* Average duration of a ride,
* Longest ride,
* Shortest ride,
* Station with the most rides as a starting place,
* Station with the most rides as an ending place,
* Month by Month breakdown of number of rides with subtotals for each year,
* Most ridden bike with total number of rides for that bike,
* Least ridden bike with total number of rides for that bike,
* User subscription type breakout with both count and percentage,
* Single date with the highest number of trips with a count of those trips,
* Single date with the lowest number of trips with a count of those trips.
Reviewers:
@AtmaVichara or …

Trip dashboard

---

app/assets/stylesheets/_trips-dashboard.scss
app/assets/stylesheets/_trips.scss
app/assets/stylesheets/application.scss
app/views/trips/index.html.erb
app/views/trips/show.html.erb
app/views/trips_dashboard/index.html.erb
spec/features/trips/user_sees_trip_dashboard_spec.rb
spec/models/trip_spec.rb

Changes Made:
* Completes model specs for trip analytics
* Adds styling for trip dashboard, trip show and trip index
Reviewers:

Trips dashboard spec cleanup and styling

---

app/views/admin/users/show.html.erb
app/views/users/show.html.erb
spec/features/authentication/admin_user_can_log_in_spec.rb

#17 
Changes Made:
Adds admin dashboard view
Adds admin and user dashboard styling
Reviewers:
@AtmaVichara or @garcia50

Admin dashboard

---

app/assets/stylesheets/_conditions.scss
app/controllers/admin/conditions_controller.rb
app/views/admin/conditions/_form.html.erb
app/views/admin/conditions/edit.html.erb
app/views/admin/conditions/index.html.erb
app/views/admin/conditions/new.html.erb
app/views/admin/conditions/show.html.erb
app/views/conditions/index.html.erb
spec/features/admins/admin_can_create_new_condition_spec.rb
spec/features/admins/admin_can_delete_conditions_spec.rb
spec/features/admins/admin_can_edit_category_spec.rb
spec/features/conditions/admin_sees_admin_category_show_spec.rb
spec/features/conditions/admin_sees_conditions_index_spec.rb
spec/features/conditions/admin_sees_single_condition_spec.rb

#14 #13 #11 #12 #15 
Changes Made:
* Add Admin Condition Crud Feature Tests (Index, Show, Create, Edit, Update)
* Add Admin::ConditionsController and Actions (index, show, new, create, edit, update, destroy)
* Add Admin Conditions View (index, show, new, edit, _form)
* All Tests Passing
Reviewers:
@memcmahon @garcia50

Admin condition crud

---

app/models/station.rb
app/views/stations_dashboard/index.html.erb
spec/factories.rb
spec/features/stations/registered_user_sees_stations_dashboard_spec.rb

Changes Made:
Finish Station Dashboard Spec
Reviewers:

Passing Station Dashboard Test

---

app/controllers/admin/trips_controller.rb
app/models/trip.rb
app/views/admin/trips/_form.html.erb
app/views/admin/trips/edit.html.erb
app/views/trips/index.html.erb
app/views/trips/show.html.erb
app/views/trips_dashboard/index.html.erb
db/seeds.rb
spec/features/trips/admin_can_delete_a_trip_spec.rb
spec/features/trips/admin_can_edit_a_trip_spec.rb
spec/features/trips/admin_sees_trip_index_spec.rb
spec/features/trips/admin_sees_trip_show_spec.rb
spec/features/trips/visitor_sees_trip_index_spec.rb
spec/features/trips/visitor_sees_trips_show_spec.rb
spec/models/trip_spec.rb

#85
Changes Made:
Adds spec and implementation for admin trip edit/delete/index/show
Updates seed structure for new trip station relationship
Updates trip tests for new relationships
Fixes trip dashboard - rides by month to group by month regardless of year.
Reviewers:
@AtmaVichara or @garcia50

Admin trip crud partial and dashboard fix

---

Gemfile
Gemfile.lock
app/models/trip.rb
db/migrate/20180222153048_add_avatar_columns_to_accessories.rb
db/schema.rb
db/seeds.rb

#89 #88
Changes Made:
Adds paperclip to gemfile
Creates migration for paperclip avatar
Creates seeds for 12 accessories (all active)
Fixes the rounding issue on the trip average duration
Reviewers:
@AtmaVichara or @garcia50

Accessory seed

---

app/models/station.rb
app/views/stations/show.html.erb
spec/features/stations/user_and_admin_sees_station_show_spec.rb

#96 
Changes Made:
Adds metrics to the station show - visible only to current user (registered user or admin)
Still need model tests for station and additional styling.
Reviewers:

Station show

---

app/models/accessory.rb
app/models/order.rb
app/models/order_accessory.rb
db/migrate/20180225000124_create_order_accessories.rb
db/schema.rb
spec/models/accessory_spec.rb
spec/models/order_accessories_spec.rb
spec/models/order_spec.rb

N/A
Changes Made:
Add relationship tests
Add join table between order and accessories
Add relationships between models
All Tests Passing
Reviewers:

Order and Accessories Join Table

---

spec/models/cart_spec.rb

N/A
Changes Made:
* Model Tests
Reviewers:

Add model tests

---

app/controllers/application_controller.rb
app/controllers/users_controller.rb
spec/features/users/visitor_security_spec.rb

Changes Made:
- Create Visitor security test
- Add check_user functionality, if there is no current user the visitor will be redirected to the root if any unauthorized paths are committed
- Add before_action to check_user for show
Reviewers:

Visitor security

---

app/controllers/orders_controller.rb
app/models/order.rb
app/views/cart/index.html.erb
app/views/layouts/application.html.erb
app/views/orders/show.html.erb
spec/models/order_spec.rb

N/A
Changes Made:
* Add Misc Styling (link to cart, subtotal, etc.)
* Add model tests
* Delete extraneous method (subtotal in cart.rb)
* All tests passing
Reviewers:
@memcmahon @garcia50

Order Misc.

---

app/views/admin/conditions/_form.html.erb
app/views/admin/stations/new.html.erb
app/views/stations/edit.html.erb
app/views/stations/show.html.erb
spec/features/admins/admin_can_create_station_spec.rb
spec/features/admins/admin_can_delete_station_spec.rb
spec/features/admins/admin_can_edit_station_spec.rb
spec/features/stations/visitor_sees_station_show_spec.rb
spec/models/station_spec.rb
spec/models/trip_spec.rb

#116 #117 
Changes Made:
Adds basic styling for station show analytics.
Adds model tests for station show analytics.
Updates trip and station to show date fields rather than text fields for dates.
Updates tests for new date formatting.
Reviewers:

Station show styling

---

app/assets/stylesheets/_forms.scss
app/controllers/admin/accessories_controller.rb
app/models/accessory.rb
app/views/accessories/index.html.erb
app/views/admin/accessories/_form.html.erb
app/views/admin/accessories/edit.html.erb
config/routes.rb
spec/features/admins/admin_can_edit_accessory_spec.rb

#122 #132 
Changes Made:
* Add spec for editing accessory
* Add paperclip to accessory
* Add file_field to form
* Add edit and update action to Admin::AccessoriesController
* Add edit view
* Delete extraneous routes
* All tests passing
Reviewers:

Paperclip & Edit Accessory

---

app/assets/stylesheets/_forms.scss
app/controllers/admin/accessories_controller.rb
app/views/accessories/index.html.erb
app/views/admin/accessories/_form.html.erb
app/views/conditions/index.html.erb
app/views/layouts/application.html.erb
config/routes.rb
spec/features/admins/admin_can_delete_accessory_spec.rb
spec/features/conditions/visitor_sees_all_conditions_spec.rb
spec/features/users/user_sees_all_conditions_spec.rb

N/A
Changes Made:
* Add styling
* Fix delete button in accessories
* Fix paperclip and image loading
* Add delete actions to controller (Admin::AccessoriesController)
* All tests passing
Reviewers:

Styling and Misc

---

app/controllers/admin/orders_controller.rb
app/controllers/admin/users_controller.rb
app/models/order.rb
app/views/admin/orders/show.html.erb
app/views/admin/users/show.html.erb
config/routes.rb
db/migrate/20180225195246_add_address_to_users.rb
db/schema.rb
spec/features/admins/admin_sees_list_of_orders_spec.rb
spec/features/orders/admin_sees_order_show_spec.rb

#18 #20 #21 #22 
Changes Made:
Adds address fields to user table
Adds admin order show
Adds orders to dashboard show
Adds functionality for admins changing order status
Reviewers:
@garcia50 @AtmaVichara

Admin orders

---

app/views/accessories/show.html.erb
spec/features/users/visitor_views_accesory_show_spec.rb

Changes Made:
Add styling to visitor views accessory show 
Reviewers:

Add styling to accessory show and create visitor accessory test

---

Gemfile
Gemfile.lock
config/aws.yml
config/environments/development.rb
config/environments/production.rb

Changes Made:
sets up for paperclip on heroku?
Reviewers:

sets up paperclip for heroku

---

app/models/accessory.rb

Changes Made:
Adds s3 region to accessory settings
Reviewers:

Adds region to s3 settings

---

app/models/accessory.rb

Changes Made:
pulls region setting out of credentials section
Reviewers:

fixes region link

---

app/models/accessory.rb

Changes Made:
updates s3 host name
Reviewers:

Updates name of region

---

app/controllers/admin/trips_controller.rb
app/models/trip.rb
app/views/admin/orders/show.html.erb
app/views/orders/show.html.erb
app/views/trips/index.html.erb

#167 #163 
Changes Made:
Added order updated date to order show (registered user view and admin views)
fixes trip create issue
Reviewers:
@AtmaVichara  @garcia50

Trip create

---

app/controllers/conditions_dashboard_controller.rb
app/controllers/orders_controller.rb
app/controllers/stations_dashboard_controller.rb
spec/features/stations/registered_user_sees_stations_dashboard_spec.rb

#152 #164
Changes Made:
Adds filter to actions to restrict access to dashboards.
Adds control to restrict access to others' carts
Reviewers:

Authorization

---

app/assets/stylesheets/skeleton.scss
app/views/accessories/show.html.erb
app/views/cart/index.html.erb
app/views/layouts/application.html.erb
spec/features/admins/admin_can_retire_accessory_spec.rb
spec/features/cart/visitor_sees_contents_of_cart_spec.rb

#157 
Changes Made:
* Add feature test for retire button
* Add cart and image to show page
* Add table and styling to cart
* Add link to sign up or login page if visitor is not logged in while trying to checkout
Reviewers:

Cart conditions work

---

app/controllers/admin/base_controller.rb
app/models/order.rb
app/views/admin/users/show.html.erb
app/views/conditions/show.html.erb
app/views/stations/index.html.erb
app/views/users/_address_form.html.erb
app/views/users/edit.html.erb
app/views/users/new.html.erb
spec/features/admins/admin_sees_list_of_orders_spec.rb
spec/features/conditions/admin_sees_single_condition_spec.rb

#134 #139 #155 #189 
Changes Made:
Adds flash notice for non-admins trying to access admin pages.
Reorders order statuses for admin dashboard show
Adds table for order show to admin dashboard
Syncs edit/delete buttons across application
Adds address fields to user edit form
Reviewers:

Check in cleanup

---

app/assets/stylesheets/skeleton.scss
app/views/cart/index.html.erb
app/views/orders/show.html.erb
app/views/users/show.html.erb

Changes Made:
* Tables to order show 
Reviewers:

Cart user misc

---

app/views/stations/index.html.erb

Changes Made:
Update date format
Reviewers:

Update date format

---

app/assets/stylesheets/skeleton.scss
app/views/conditions/show.html.erb
app/views/stations/index.html.erb
app/views/stations/show.html.erb
app/views/trips/index.html.erb
app/views/trips/show.html.erb

#181 
Changes Made:
Bolds labels on indexes and show views
Reviewers:

Adds bolding to index and show labels

---

app/assets/stylesheets/_trips.scss
app/assets/stylesheets/skeleton.scss
app/models/station.rb
app/views/welcome/index.html.erb

#179 
Changes Made:
Adds a basic welcome page.
fixes station so that if deleted, the trips are deleted as well (so that trip index doesn't crash)
Reviewers:

Welcome page

---

app/assets/stylesheets/_bike-shop.scss
app/assets/stylesheets/application.scss
app/views/accessories/index.html.erb
spec/features/orders/registered_user_can_view_single_order_spec.rb
spec/features/orders/registered_user_submits_an_order_spec.rb
spec/features/stations/visitor_sees_station_index_spec.rb

Changes Made:
* Fixed tests that broke from previous work
Reviewers:
@memcmahon @garcia50

Fix tests & Accessory Create Styling

---

app/assets/stylesheets/_carts.scss
app/views/admin/accessories/edit.html.erb
app/views/admin/conditions/edit.html.erb
app/views/admin/conditions/new.html.erb
app/views/admin/orders/show.html.erb
app/views/admin/stations/new.html.erb
app/views/admin/trips/edit.html.erb
app/views/admin/trips/new.html.erb
app/views/cart/index.html.erb
app/views/layouts/application.html.erb
app/views/stations/edit.html.erb
app/views/stations/index.html.erb
app/views/users/edit.html.erb
spec/features/admins/admin_can_see_index_of_accessories_spec.rb
spec/features/orders/admin_sees_order_show_spec.rb

#219 #222 #222 #214 #221 #213
Changes Made:
* Add minor styling
Reviewers:
@memcmahon @garcia50

Minor fixes

---

app/assets/stylesheets/skeleton.scss
app/controllers/admin/base_controller.rb
app/models/station.rb
app/models/trip.rb
app/views/admin/trips/_form.html.erb
app/views/trips_dashboard/index.html.erb
spec/features/trips/admin_can_create_a_new_trip_spec.rb
spec/features/trips/admin_can_edit_a_trip_spec.rb
spec/models/trip_spec.rb

#211 #217 #220 #216 #212 #218 
Changes Made:
Fixes dashboard for use after new trip created
Removes erroneous flash message for admin required
Adds sorting to trip model
Adds N/A to station dashboard analytics if none
Increases font size for index labels
Reviewers:
@garcia50 @AtmaVichara

Final cleanup

---

app/models/application_record.rb
app/views/admin/accessories/index.html.erb
app/views/admin/orders/show.html.erb
app/views/admin/users/show.html.erb
app/views/orders/show.html.erb
app/views/users/show.html.erb
spec/features/orders/admin_sees_order_show_spec.rb

Changes Made:
Move Money Gem globally
Reviewers:

Mo money Mo Problems

---

app/assets/stylesheets/_bike-shop.scss
app/assets/stylesheets/skeleton.scss
app/controllers/admin/accessories_controller.rb

Changes Made:
Updates panel images to clean up grid spacing on accessories.
Reviewers:

Accessory style cleanup
